include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - /**/*.pb.dart
    - /**/*.pbenum.dart
    - /**/*.pbgrpc.dart
    - /**/*.pbjson.dart
    - /**/*.pbserver.dart
    - /**/*.mocks.dart
