name: Client

on:
  push:

defaults:
  run:
    shell: bash
    working-directory: client

jobs:
  generate:
    name: Regenerate files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.3"
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - name: Install tools
        run: make install
      - name: Regenerate files
        run: make generate
      - name: Check for a diff
        run: git diff --exit-code

  test:
    name: Test
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.3"
      - name: Test
        run: make unit-test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          files: ./client/coverage/Icov.info
          flags: unittests
          fail_ci_if_error: false
          verbose: true

  lint:
    name: Lint
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.3"
      - name: Lint
        run: make lint
