name: Server

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: server

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install tools
        run: make install
      - name: Test
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          flags: unittests
          fail_ci_if_error: false
          verbose: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install tools
        run: make install
      - name: Lint
        run: make lint

  generate:
    name: Regenerate files
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install tools
        run: make install
      - name: Regenerate files
        run: make generate
      - name: Check for a diff
        run: git diff --exit-code
