name: Server Release

on:
  push:
  # create:
  #   tags:
  #     - v\d+.\d+.\d+

defaults:
  run:
    shell: bash
    working-directory: server

jobs:
  build_docker:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Set env release version
      #   run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set env release version
        run: echo "RELEASE_VERSION=v.0.0.1" >> $GITHUB_ENV
      - name: Show release version
        run: echo $env.RELEASE_VERSION
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/iakrevetkho/dots/server:latest
            ghcr.io/iakrevetkho/dots/server:$env.RELEASE_VERSION
